verbose: false
instrumentation:
    root: ./src
    extensions:
        - .js
    default-excludes: true
    #excludes: ['**/tinymce/**', '**/lib/**', '**/tools/**', '**/build/**']
    #excludes: ['server.js', 'index.js', 'routes/**']
    embed-source: false
    variable: __coverage__
    compact: true
    preserve-comments: false
    complete-copy: false
    save-baseline: false
    baseline-file: ./coverage/coverage-baseline.json
    include-all-sources: true
    include-pid: false
    es-modules: false
reporting:
    print: summary
    reports:
        - lcov
    dir: ./coverage
    watermarks:
        statements: [50, 85] # Coverage - <50 Low / < 80 Med / > 80 High 
        lines: [50, 85]
        functions: [50, 85]
        branches: [50, 85]
    report-config:
        # clover: {file: clover.xml}
        # cobertura: {file: cobertura-coverage.xml}
        # json: {file: coverage-final.json}
        # json-summary: {file: coverage-summary.json}
        # lcovonly: {file: lcov.info}
        # teamcity: {file: tc.cov, blockName: Code Coverage Summary}
        # text: {file: null, maxCols: 0}
        # text-lcov: {file: lcov.info}
        # text-summary: {file: null}
hooks:
    hook-run-in-context: false
    post-require-hook: null
    handle-sigint: false
check:
    global:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
        excludes: []
    each:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
        excludes: []